// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoCore.Models;

#nullable disable

namespace ProyectoCore.Migrations
{
    [DbContext(typeof(TiendaPruebaContext))]
    partial class TiendaPruebaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ListaProducto", b =>
                {
                    b.Property<int>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Lista");

                    b.Property<int>("IdProductos")
                        .HasColumnType("int")
                        .HasColumnName("Id_Productos");

                    b.HasKey("IdLista", "IdProductos")
                        .HasName("PK__Lista_Pr__7B37C322EAD40186");

                    b.HasIndex("IdProductos");

                    b.ToTable("Lista_Producto", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.Carrito", b =>
                {
                    b.Property<int>("IdCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_carrito");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarrito"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.HasKey("IdCarrito")
                        .HasName("PK__Carrito__195A55BF7E235BE4");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Carrito", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.CarritoProducto", b =>
                {
                    b.Property<int>("IdCarrito")
                        .HasColumnType("int")
                        .HasColumnName("Id_carrito");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<double?>("Precio")
                        .HasColumnType("float");

                    b.HasKey("IdCarrito", "IdProducto")
                        .HasName("PK__Carrito___1882BA4FA452C27B");

                    b.HasIndex("IdProducto");

                    b.ToTable("Carrito_productos", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.Categorium", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria")
                        .HasName("PK__Categori__CB90334942F4F8AF");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ProyectoCore.Models.ListaDeseo", b =>
                {
                    b.Property<int>("IdLista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Lista");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLista"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.HasKey("IdLista")
                        .HasName("PK__Lista_de__FD5DC8F4B84E07AD");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Lista_deseos", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.ListaProducto", b =>
                {
                    b.Property<int>("IDListaProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_Lista");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.HasKey("IDListaProducto", "IdProducto")
                        .HasName("PK__ListaProducto___1882BA4FA452C27B");

                    b.HasIndex("IdProducto");

                    b.ToTable("Lista_Productos", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_metodo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodo"));

                    b.Property<string>("TipoMetodo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tipo_metodo");

                    b.HasKey("IdMetodo")
                        .HasName("PK__Metodo_p__AB62E2F251AC33E5");

                    b.ToTable("Metodo_pago", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("Id_categoria");

                    b.Property<byte[]>("Imagen")
                        .HasColumnType("image");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<double?>("Precio")
                        .HasColumnType("float")
                        .HasColumnName("precio");

                    b.Property<int?>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto")
                        .HasName("PK__Producto__1D8EFF01E2719CCB");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProyectoCore.Models.Recibo", b =>
                {
                    b.Property<int>("IdRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Recibo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecibo"));

                    b.Property<string>("Campo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdCarrito")
                        .HasColumnType("int")
                        .HasColumnName("Id_Carrito");

                    b.Property<int?>("IdMetodoPago")
                        .HasColumnType("int")
                        .HasColumnName("Id_metodo_pago");

                    b.Property<double?>("Impuestos")
                        .HasColumnType("float")
                        .HasColumnName("impuestos");

                    b.Property<double?>("Subtotal")
                        .HasColumnType("float")
                        .HasColumnName("subtotal");

                    b.HasKey("IdRecibo")
                        .HasName("PK__Recibo__3854E199AA3E8DBE");

                    b.HasIndex("IdCarrito");

                    b.HasIndex("IdMetodoPago");

                    b.ToTable("Recibo", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.Reseña", b =>
                {
                    b.Property<int>("IdReseña")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Reseña");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReseña"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("comentario");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("Id_producto");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.Property<int?>("ValorReseña")
                        .HasColumnType("int")
                        .HasColumnName("valor_reseña");

                    b.HasKey("IdReseña")
                        .HasName("PK__Reseña__D2EBE05CC1157BD1");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Reseña", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.Role", b =>
                {
                    b.Property<int>("IdRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Roles");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoles"));

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRoles")
                        .HasName("PK__Roles__2610294B1830CE76");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoCore.Models.RolesUsuario", b =>
                {
                    b.Property<int>("IdRoles")
                        .HasColumnType("int")
                        .HasColumnName("Id_Roles");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.HasKey("IdRoles", "IdUsuario")
                        .HasName("PK__RoleUsuario___1882BA4FA452C27B");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Roles_Usuario", (string)null);
                });

            modelBuilder.Entity("ProyectoCore.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContraseñaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dirección")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("Email")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("Fecha_Nacimiento");

                    b.Property<string>("Nombre")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)")
                        .HasColumnName("Nombre_Usuario");

                    b.Property<string>("Teléfono")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__DE4431C5E8A8D105");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("RolesUsuario", b =>
                {
                    b.Property<int>("IdRoles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Roles");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("Id_Usuario");

                    b.HasKey("IdRoles", "IdUsuario")
                        .HasName("PK__Roles_us__102C5FF567E63D1D");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Roles_usuario", (string)null);
                });

            modelBuilder.Entity("ListaProducto", b =>
                {
                    b.HasOne("ProyectoCore.Models.ListaDeseo", null)
                        .WithMany()
                        .HasForeignKey("IdLista")
                        .IsRequired()
                        .HasConstraintName("FK__Lista_Pro__Id_Li__534D60F1");

                    b.HasOne("ProyectoCore.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("IdProductos")
                        .IsRequired()
                        .HasConstraintName("FK__Lista_Pro__Id_Pr__5441852A");
                });

            modelBuilder.Entity("ProyectoCore.Models.Carrito", b =>
                {
                    b.HasOne("ProyectoCore.Models.Usuario", "oUsuario")
                        .WithMany("Carritos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Carrito__Id_Usua__4316F928");

                    b.Navigation("oUsuario");
                });

            modelBuilder.Entity("ProyectoCore.Models.CarritoProducto", b =>
                {
                    b.HasOne("ProyectoCore.Models.Carrito", "oCarrito")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("IdCarrito")
                        .IsRequired()
                        .HasConstraintName("FK__Carrito_p__Id_ca__4CA06362");

                    b.HasOne("ProyectoCore.Models.Producto", "oProducto")
                        .WithMany("CarritoProductos")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__Carrito_p__Id_pr__4D94879B");

                    b.Navigation("oCarrito");

                    b.Navigation("oProducto");
                });

            modelBuilder.Entity("ProyectoCore.Models.ListaDeseo", b =>
                {
                    b.HasOne("ProyectoCore.Models.Usuario", "oUsuario")
                        .WithMany("ListaDeseos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Lista_des__Id_Us__5070F446");

                    b.Navigation("oUsuario");
                });

            modelBuilder.Entity("ProyectoCore.Models.ListaProducto", b =>
                {
                    b.HasOne("ProyectoCore.Models.ListaDeseo", "oListaDeseo")
                        .WithMany("IDListaProducto")
                        .HasForeignKey("IDListaProducto")
                        .IsRequired()
                        .HasConstraintName("FK__ListaProducto_p__Id_ca__4CA06362");

                    b.HasOne("ProyectoCore.Models.Producto", "oProducto")
                        .WithMany("IDListaProducto")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK__ListaProducto_p__Id_pr__4D94879B");

                    b.Navigation("oListaDeseo");

                    b.Navigation("oProducto");
                });

            modelBuilder.Entity("ProyectoCore.Models.Producto", b =>
                {
                    b.HasOne("ProyectoCore.Models.Categorium", "oCategorium")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK__Productos__Id_ca__49C3F6B7");

                    b.Navigation("oCategorium");
                });

            modelBuilder.Entity("ProyectoCore.Models.Recibo", b =>
                {
                    b.HasOne("ProyectoCore.Models.Carrito", "oCarrito")
                        .WithMany("Recibos")
                        .HasForeignKey("IdCarrito")
                        .HasConstraintName("FK__Recibo__Id_Carri__46E78A0C");

                    b.HasOne("ProyectoCore.Models.MetodoPago", "oMetodoPago")
                        .WithMany("Recibos")
                        .HasForeignKey("IdMetodoPago")
                        .HasConstraintName("FK__Recibo__Id_metod__45F365D3");

                    b.Navigation("oCarrito");

                    b.Navigation("oMetodoPago");
                });

            modelBuilder.Entity("ProyectoCore.Models.Reseña", b =>
                {
                    b.HasOne("ProyectoCore.Models.Producto", "oProducto")
                        .WithMany("Reseñas")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK__Reseña__Id_produ__5812160E");

                    b.HasOne("ProyectoCore.Models.Usuario", "oUsuario")
                        .WithMany("Reseñas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Reseña__Id_Usuar__571DF1D5");

                    b.Navigation("oProducto");

                    b.Navigation("oUsuario");
                });

            modelBuilder.Entity("ProyectoCore.Models.RolesUsuario", b =>
                {
                    b.HasOne("ProyectoCore.Models.Role", "oRole")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("IdRoles")
                        .IsRequired()
                        .HasConstraintName("FK__RolesUsuario_U__Id_ca__4CA06362");

                    b.HasOne("ProyectoCore.Models.Usuario", "oUsuario")
                        .WithMany("RolesUsuarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__RolesUsuario_p__Id_pr__4D94879B");

                    b.Navigation("oRole");

                    b.Navigation("oUsuario");
                });

            modelBuilder.Entity("RolesUsuario", b =>
                {
                    b.HasOne("ProyectoCore.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRoles")
                        .IsRequired()
                        .HasConstraintName("FK__Roles_usu__Id_Ro__3F466844");

                    b.HasOne("ProyectoCore.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__Roles_usu__Id_Us__403A8C7D");
                });

            modelBuilder.Entity("ProyectoCore.Models.Carrito", b =>
                {
                    b.Navigation("CarritoProductos");

                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("ProyectoCore.Models.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ProyectoCore.Models.ListaDeseo", b =>
                {
                    b.Navigation("IDListaProducto");
                });

            modelBuilder.Entity("ProyectoCore.Models.MetodoPago", b =>
                {
                    b.Navigation("Recibos");
                });

            modelBuilder.Entity("ProyectoCore.Models.Producto", b =>
                {
                    b.Navigation("CarritoProductos");

                    b.Navigation("IDListaProducto");

                    b.Navigation("Reseñas");
                });

            modelBuilder.Entity("ProyectoCore.Models.Role", b =>
                {
                    b.Navigation("RolesUsuarios");
                });

            modelBuilder.Entity("ProyectoCore.Models.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("ListaDeseos");

                    b.Navigation("Reseñas");

                    b.Navigation("RolesUsuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
